### ISSUE TITLE
Werkpakket: taxonomische concepten - imbor/imgeo

### ISSUE THREAD

**Issue by NielsHoffmann** [bimloket/CB-NL#19]
Niels R. Rik + Niels H.

**Comment by RiX012** [comment]
1.	Ik heb de laatste werkversie van IMBOR2021 gepakt
2.	Daar de vocabulaire gefilterd op de collecties: Objecttype, Klasse, InformatieObject, ObjecttypeOnderdeel.
3.	Hier de kolom Vakdiscipline aan toegevoegd (geldt alleen voor Objecttypen.
4.	Deze naar Excel gehaald en ontdubbeld (meerdere Objecttype <> Vakdiscipline combinaties zijn mogelijk)
5.	Eerste alle Klasse, InformatieObject en ObjecttypeOnderdeel beoordeeld of ze mogelijk interessant zijn voor een topmodel als de CB-NL.
6.	Vervolgens per Vakdiscipline alle Objecttype beoordeeld

De definities van Klasse zijn een beetje gekunsteld, want het betreffen hier eigenlijk ‘groepjes van gegevens’. Maar hier ben ik maar even afgegaan op wat de term voorstelt…

Zoals je ziet houd ik er maar heel weinig over. Dit heb ik gedaan met deze ‘principes’ in mijn achterhoofd:
-	Is het een generiek toepasbaar concept (over alle sectoren)
-	Vind ik dat het één of maximaal twee hiërarchie niveaus onder de NEN2660-2 elementen zit
-	Denk ik dat het een concept is waarmee iemand makkelijker kan begrijpen wat het NEN2660-2 element praktisch inhoud

[IMBOR-2021-04-04 CBnl selectie.xlsx](https://github.com/bimloket/CB-NL/files/6390044/IMBOR-2021-04-04.CBnl.selectie.xlsx)

**Comment by RiX012** [comment]
Voor de skos input is hier de file gemaakt (adhv ontologie van Bart)
https://github.com/bimloket/CB-NL/tree/main/ontology/input

**Comment by mickbaggen** [comment]
Het valt me op dat er twee stijlen van definities zijn in imbor 2021 beta:

1) Brug: Kunstwerk over een waterweg, watergang of waterloop, bestaande uit een brugdek gesteund door pijlers en/of landhoofden
2) Bouwwerk: Gegevens die specifiek zijn voor voor met de aarde verbonden duurzaam bouwwerk, dat niet valt onder de definities van een pand of kunstwerk

Stijl 1 is volgens mij prima (de definitie beschrijft een object met onderscheidende kenmerken), stijl 2 is merkwaardig: het gaat plots over gegevens over iets, maar niet het object zelf. 

Ik stel voor om in IMBOR zelf de definitie voor Bouwwerk aan te passen naar: "met de aarde verbonden duurzaam bouwwerk, dat niet valt onder de definities van een pand of kunstwerk". Dat geldt ook voor alle andere concepten, waarbij in de definitie wordt gesproken over "gegevens" of "registratie" of "begrenzing".

PS een IMBOR Concept "Postcode" heeft ook een merkwaardige definitie "Begrenzing van een postcodegebied (6 posities)". Hier vindt vermenging plaats van enerzijds de GIS representatie van een postcode gebied, en anderzijds het concept "postcode gebied" zelf. Ofwel: de definitie moet antwoord geven op de vraag: "Wat IS een postcode gebied", niet "hoe representeer je een postcode gebied?".

Dan blijft wel een ander issue over: de definitie is circulair.

**Comment by RiX012** [comment]
Thanks @mickbaggen, je conclusies zijn helemaal correct. Voor stijl 1 en stijl 2 kan ik beargumenteren waarom dat nu zo is (respectievelijk 'groepering van attributen' en 'snelheid van de data vraag in applicaties), maar feit is dat het gewoon heel raar is. Ik ben het hier ook helemaal niet mee eens. Vandaar dat we in IMBOR2021 dit compleet aan het herzien zijn en we ons enten op de NEN2660-2, MIM en NEN3610. 
Jouw voorstellen kan ik zeker wat mee.

**Comment by RiX012** [comment]
@bartbink De verSKOSsing staat nu in de /input/ map
