### ISSUE TITLE
Werkpakket: taxonomische concepten - 2767

### ISSUE THREAD

**Issue by NielsHoffmann** [bimloket/CB-NL#20]
Lucas, Paul

**Comment by LucasVerhelst** [comment]
Paul en ik hebben een begin gemaakt met de filtering van NEN 2767-4.

We komen daarbij op de volgende criteria voor het meenemen van een objecttype:
- Er is een groot aantal instanties/het wordt veel gebruikt (schatting)
- Het is een belangrijk objecttype waar veel informatie over wordt bijgehouden (bijv. Stormvloedkering)
- Het objecttype past bij het doel van de standaard (ruimtelijke objecten worden bijv. meer gebruikt vanuit andere standaarden dan de NEN 2767-4)

Daarnaast hebben we als knock-out gehanteerd:
- Er is geen definitie beschikbaar (bijv. de restcategorieën in de NEN 2767-4, waarvan de naam eindigt met "Algemeen")

**Comment by LucasVerhelst** [comment]
Uit de werksessie van 7-5-2021 die @PaulHaase12 en ik hebben gehad is de volgend opzet gekomen:
[NEN2767-4+NEN2660+CB-NL.zip](https://github.com/bimloket/CB-NL/files/6467564/NEN2767-4%2BNEN2660%2BCB-NL.zip)

Deze is ook besproken in de Modelleurs update van vandaag.

**Comment by nreyngou** [comment]
[Controle linkset NEN2667-4 NR.xlsx](https://github.com/bimloket/CB-NL/files/7283280/Controle.linkset.NEN2667-4.NR.xlsx)
 Controle van de door Paul gemaakte linkset. Commentaar is reeds naar Paul toegezonden; ik zet hem hier puur voor de volledigheid ook nog even neer.
