### ISSUE TITLE
Werkpakket: concepten uit NLCS

### ISSUE THREAD

**Issue by nreyngou** [bimloket/CB-NL#27]
[NLCS concepten.xlsx](https://github.com/bimloket/CB-NL/files/6514524/NLCS.concepten.xlsx)

Een eerste aanzet tot filtering van de NLCS concepten. Ik heb de 29 Excelsheets met kaartlagen onder elkaar gezet. Dit leidt tot 3.470 kaartlagen. Ben er doorheen gegaan om de meest algemene te selecteren. Deze hebben in kolom E de waarde 'Ja' gekregen. Voor sommige concepten geldt dat ik ze een meer 'algemene' naam heb gegeven in kolom F. 

Het is echt een eerste poging en ik denk dat er nog te veel concepten overblijven.

Definities zijn helaas niet aanwezig in de NLCS. Ik heb dit geverifieerd bij Dik Spekkink, die eerder betrokken is geweest bij het maken van een mapping van de NLCS aan de huidige CB_NL.

**Comment by hennystolwijk** [comment]
Niels,
In het document onder de link is kolom E en F niet gevuld.

**Comment by nreyngou** [comment]
Excuus, ik had per ongeluk een oude versie geüpload. Ik heb inmiddels de juiste versie in het bericht gezet.

**Comment by hennystolwijk** [comment]
Dankjewel.

Van: NielsReyngoud ***@***.***>
Verzonden: donderdag 20 mei 2021 11:18
Aan: bimloket/CB-NL ***@***.***>
CC: Henny Stolwijk | BIM Loket ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [bimloket/CB-NL] Werkpakket: concepten uit NLCS (#27)


Excuus, ik had per ongeluk een oude versie geüpload. Ik heb inmiddels de juiste versie in het bericht gezet.

**Comment by nreyngou** [comment]
Bijgewerkte versie door Henny met het voorstel een aantal concepten niet op te nemen (de geel gemarkeerde concepten).
[Uploading NLCS.concepten (1).xlsx…]()

**Comment by nreyngou** [comment]
[NLCS.concepten_2021-06-16.xlsx](https://github.com/bimloket/CB-NL/files/6661948/NLCS.concepten_2021-06-16.xlsx)

Henny en ik hebben de concepten nogmaals doorlopen en een en ander geschapt. We komen nu uit op deze 62 concepten voor in het kernmodel.

**Comment by nreyngou** [comment]
Excelsheet aangevuld met kolom 'Opnemen in CB_NL thesaurus' en 'Broader'.

[NLCS.concepten_2021-06-22.xlsx](https://github.com/bimloket/CB-NL/files/6694164/NLCS.concepten_2021-06-22.xlsx)

**Comment by RiX012** [comment]
@bartbink De verSKOSsing staat nu in de /input/ map
