### ISSUE TITLE
Architectuurbesluit 'taalbindingen'

### ISSUE THREAD

**Issue by NielsHoffmann** [bimloket/CB-NL#3]
De huidige CB-NL is in OWL gemodelleerd.
In de NEN2660 wordt onderscheid gemaakt in 3 niveaus van 'taalbinding'. Deze 3 niveaus ondersteunen verschillende informatiebehoeften. 
Uitwerken hoe de CB-NL hierin wil voorzien.

**Comment by RiX012** [comment]
Mijn interpretatie van onze ideeën na meeting 1:
[https://github.com/bimloket/CB-NL/blob/main/bijlagen/CB-NL-1e-ArchitectuurOpzet.png](https://github.com/bimloket/CB-NL/blob/main/bijlagen/CB-NL-1e-ArchitectuurOpzet.png)

**Comment by NielsHoffmann** [comment]
besproken in de vergadering van 15-4-2021:

VOCABULAIRE
Er wordt een vocabulaire gemaakt en een taxonomie. De vocabulaire wordt uitgedrukt in SKOS concepten met een voorkeursdefinitie. In de definitie worden de definiërende zaken/eigenschappen meegenomen.
Het woordenboek kan op deze manier worden hergebruikt op een laagdrempelige wijze wat de adaptatie van het kernmodel bespoedigt.
Bart maakt een template voor het woordenboek met metadata voor het beheer van de concepten en definities. Zo krijgt iedere definitie een bronvermelding. Er kunnen meerdere definities aan een concept hangen. Eén van de definities is de voorkeursdefinitie.

TAXONOMIE
De Taxonomie wordt opgebouwd uit de concepten van de vocabulaire. De hiërarchie wordt bepaalt door de definitie. De definitie kan worden aangescherpt of aangevuld a.d.h.v. de plek in de taxonomie.
De taxonomie wordt geschreven in rdf/rdfs en niet in skos. Er wordt naar skos concepten verwezen door rdfs:isDefinedBy. De subtypering wordt gedefinieerd door rdfs:subClassOf en niet skos:narrower.
De taxonomie mag multiple inheritance gebruiken. Hoe de definitie wordt uitgeschreven is tijdens de meeting nog een punt van discussie.
De taxonomie is er om te ‘extenden’ en niet om te mappen.

**Comment by NielsHoffmann** [comment]
Wat ik me nog wel afvraag en niet zie terugkomen in het gespreksverslag of het plaatje van Rik is hoe we omgaan met de verschillende 'dimensies' uit de NEN2660. 
In de NEN2660 wordt het onderscheid gemaakt tussen ReeelObject <-> RuimtelijkGebied. Maar ook tussen FunctioneleEntiteit <-> TechnischeEntiteit en GeplandeEntiteit <-> GerealiseerdeEntiteit

Er wordt wel gesteld dat er in de taxonomie multiple inheritance mag voorkomen, maar er wordt niet expliciet gemaakt of dat bedoelt is om deze 'dimensies' te addresseren
