### ISSUE TITLE
filenamen van TTL files

### ISSUE THREAD

**Issue by bartbink** [bimloket/CB-NL#32]
Volg kwa filenamen de nen2660 aanpak…..huidige namen zijn volgens de ‘name spaces uris’….beter volgens de ‘base/graaf uris’ ….

Dus bv cbnl-skos.ttl, cbnl-rdfs.ttl, cbnl-owl.rdfs etc.

Fijn weekend,
Michel

**Comment by ElisabethKloren** [comment]
volgens mij is dit gedaan, toch @bartbink?

**Comment by bartbink** [comment]
no comment
