### ISSUE TITLE
<https://bimloket.nl/data/term/cbnl/1c1a4dd1-93e5-42ba-bbb1-269c2a7d1ee3> nl preflabel fout 

### ISSUE THREAD

**Issue by NielsHoffmann** [bimloket/CB-NL#34]
is nu samensel zal wel samenstelling moeten zijn?

**Comment by NielsHoffmann** [comment]
en waarom is het eigenlijk een smaller concept van Discreet object? Voelt niet logisch en als je de class hierarchie ernaast zet is het equivalent 'smanehangend geheel' wat een groep->rdfs:Container is....

**Comment by bartbink** [comment]
Het moet samenstelling zijn (Engelse term is assembly ,die kan ook beter trouwens). Het gaat hier om een fysieke of informatie samenstelling.
