### ISSUE TITLE
uitleg van de 'dubbele hierarchie' (skos en rdfs)

### ISSUE THREAD

**Issue by NielsHoffmann** [bimloket/CB-NL#35]
Ik heb de discussies natuurlijk gedeeltelijk meegemaakt (en gedeeltelijk aangezwengeld)
Maar ik denk dat een 'buitenstaander' er geen hout van snapt dat er zowel een SKOS hierarchie als een RDFS hierarchie is.
documentatie zal dit goed uit moeten leggen. Hier in de repo als mensen hier terecht komen en op een 'landingspage' bij de viewer...

**Comment by ElisabethKloren** [comment]
Erg mee eens. Een deel van de uitleg staat hier: https://bimloket.github.io/CB-NL/spelregels/. Nog steeds licht onbegrijpelijk uiteraard. Ik heb ook deze geupdated: https://github.com/bimloket/CB-NL/blob/main/ontology/readme.md

Deze vraag is licht achterhaald, nu we het advies willen volgen om van CB-NL alleen de skos versie te gaan inzetten als begrippenbibliotheek. Ik sluit deze issue voor nu.
