### ISSUE TITLE
relaties rond de term en de class watersysteem lijken niet helemaal logisch te zijn

### ISSUE THREAD

**Issue by NielsHoffmann** [bimloket/CB-NL#36]
de term watersysteem voert terug naar de term fysiek object, terwijl de class watersysteem een subclass van rdfs:Container is (en niet van PhysicalObject voor zover ik kan nagaan)

**Comment by bartbink** [comment]
de term watersysteem voert terug naar de term fysiek object, waar staat dat? In de definitie staat: Samenhangend geheel van een of meer oppervlaktewaterlichamen en grondwaterlichamen, met bijbehorende bergingsgebieden, waterkeringen en ondersteunende kunstwerken; (bron: Waterwet). Een samenhangend geheel is een eigen concept, dus als de definitie wordt gevolgd, staat watersysteem goed.
