### ISSUE TITLE
abstract object

### ISSUE THREAD

**Issue by lruijv** [bimloket/CB-NL#37]
mis de definitie van abstract object.   prefereer de definitie van ISO 15926: is a Thing that does not exist in space-time
als tegenhanger geldt dan voor  concrete object: is a Thing that exists in space and time.
in principe zijn abstracte objecten niet te instantiëren.
Hiermee horen de fysieke grootheden  en eenheden die nu onder concrete object staan ook onder abstract object te staan
ook dingen als klasse zijn abstracte dingen, zonder context hebben deze dingen geen betekenis en zullen ook niet worden geïnstantieerd

**Comment by ElisabethKloren** [comment]
Hoe verhoudt dit zich tot de NEN 2660-2?

**Comment by bartbink** [comment]
Dit is aangepast. Was kennelijk verkeerd geimporteerd/aangeleverd. Het is een NEN2660 concept die de CBNL als gegeven ziet
