### ISSUE TITLE
activiteit - denken

### ISSUE THREAD

**Issue by lruijv** [bimloket/CB-NL#38]
de specialisatie structuur mentale activiteit - denken - observeren is erg arbitrair.... houd het simpel , is erg ver gedacht dat observeren een specialisatie van denken is,  kan net zo goed van redeneren zijn. daarnaast kunnen de meeste z.g. denk-activiteiten uitgevoerd kunnen worden door (AI )systemen waarbij het voorlopig te ver gaat om dat denken te noemen
definieer observeren gewoon als activiteit  CBNL is een technische taxonomie, geen filosofische taxonomie.

**Comment by ElisabethKloren** [comment]
Hier ben ik het erg mee eens - laten we het houden op concepten die in de standaarden voorkomen en niet daarbuiten gaan.

**Comment by bartbink** [comment]
denken is alleen in de skos binding een subclass van mentale activiteit. Niet in het kernmodel. Dit is precies het doel van het kernmodel. In het kernmodel zijn die zaken opgenomen waarover overeenstemming is. De rest is opgenomen in de verzamelbak (niet ter publicatie) 'nog ongeclassificeerd.
