### ISSUE TITLE
systeem - installatie

### ISSUE THREAD

**Issue by lruijv** [bimloket/CB-NL#39]
onderscheid systemen van installaties.    Systemen liggen op functioneel niveau ( subclass van functionele entiteit (zie Functional Object in ISO 15926)  en worden gerealiseerd door installaties. nu komt het begrip systeem gemixed voor
 Een systeem bestaat ook uit zowel geplande and gerealiseerde functionele en technische objecten. Zie ook NEN2660

**Comment by bartbink** [comment]
systeem is nu subclass van Functional Entity
