### ISSUE TITLE
hierachie E&M  equipment

### ISSUE THREAD

**Issue by lruijv** [bimloket/CB-NL#40]
in de praktijk blijkt de hiërarchie conform IFC4 voor E&M equipment goed te werken (doen we in de RDL van  Pallas project ook)
 zie bijgaande screendump. Op deze wijze is ook ETIM in de huidige CBNL ondergebracht,  De mapping met ETIM is overigens  essentieel voor de installatie branche.  veel van de nu nog on-geclassificeerde concepten kunnen hierin ondergebracht worden
![image](https://user-images.githubusercontent.com/94825189/142825798-5862a1e9-6458-4673-b762-5cbd4685b72a.png)

**Comment by ElisabethKloren** [comment]
ETIM is zo te zien linkbaar gepubliceerd in [bSDD](https://www.buildingsmart.org/users/services/buildingsmart-data-dictionary/) / zie ook hun github https://github.com/buildingSMART/bSDD

**Comment by ElisabethKloren** [comment]
De hiërarchie van ETIM is héél verschillend van die van de NEN 2660-2, we kunnen heel moeilijk meerdere hiërarchiën door elkaar heen gaan mixen. Dit gaan we helaas niet overnemen,
