### ISSUE TITLE
passieve actieve functionele entiteit

### ISSUE THREAD

**Issue by lruijv** [bimloket/CB-NL#41]
de opdeling naar passieve / actieve functionele entiteit was volgens mij in NEN 2660 er uit gehaald, in ieder geval begrijpt in de praktijk  niemand deze termen
daarbij zijn  bv functie en maatregel gewoon subklassen van activiteit

![image](https://user-images.githubusercontent.com/94825189/142826767-a8d9006b-4aac-4a5b-b374-1f2ae832fe80.png)

**Comment by bartbink** [comment]
Deze laten we achterwegen

**Comment by ElisabethKloren** [comment]
Deze tussenpausen halen we we ertussenuit
