### ISSUE TITLE
grootheden

### ISSUE THREAD

**Issue by lruijv** [bimloket/CB-NL#42]
mis het onderscheid naar kwalitatieve en kwantitatieve grootheden ( beiden overigens een abstract object) .  volgens mij is prijs bv gewoon een kwantitatieve grootheid ( = getal met eenheid) staat nu onder economische waarde wat dus ook een kwantitatieve grootheid is. ( en mogelijk ook kwalitatief is uit te drukken)
 ook een verzameling van kwalificaties hoort thuis onder abstract object:  zie bv de kwalificaties bij ETIM

**Comment by ElisabethKloren** [comment]
Hoe verhoudt zich dit tot de NEN 2660-2?

**Comment by ElisabethKloren** [comment]
grootheden zijn inmiddels buiten scope
