### ISSUE TITLE
mens

### ISSUE THREAD

**Issue by lruijv** [bimloket/CB-NL#45]
mens is nu subclass of dier, mi  is mens een subclass van organisme  ( zie ISO 15926)

**Comment by bartbink** [comment]
Als de biologie wordt gevolgd: De mens (homo sapiens), behooert tot het dierenrijk, de stam gewervelden, de klasse zoogdieren, de orde primaten en de familie mensachtigen.

Het ligt helemaal aan het doel/context van de CBNL. Je kan ook stellen dat er mensen zijn en dieren onder organisme.
