### ISSUE TITLE
Voorstel opnemen 'generieke begrippen'

### ISSUE THREAD

**Issue by NielsHoffmann** [bimloket/CB-NL#5]
Mick heeft een [lijst ](https://github.com/bimloket/CB-NL/blob/main/bijlagen/CB-NL%20begrippen.xlsx) opgesteld met begrippen die als 'ankerpunten' in de taxonomie opgenomen kunnen worden om richting te geven aan de invulling van de structuur.

**Comment by NielsHoffmann** [comment]
aanvulling van Mick: Dit is NIET een lijst van begrippen, die in mijn ogen allemaal een plaats in het CB-NL kernmodel (lees: taxonomie) moeten krijgen. Maar het is WEL een lijst van begrippen, die je veelvuldig tegenkomt in allerlei ordeningssystemen rondom (fysieke) objecten, maar die tegelijkertijd uitblinken in dubbelzinnigheid c.q. semantische vaagheid: deze begrippen vertellen je niet zozeer wat iets is, maar hebben allemaal een functionele bijsmaak. Niet het soort lijst dat ik normaal dus zou willen aanbevelen, maar juist om zo vroeg mogelijk met elkaar af te spreken wat we met dit soort semantische vaagheid gaan doen. Het is dus meer een “anti-lijst”…

**Comment by bartbink** [comment]
Ik heb op ons afgelopen besluit een vocabulair te maken een ontologietje gedefinieerd waarin een concept kan worden geinstantieeerd met verplicht een definitie en een bronvermelding en tot 4 alternatieve definities kan hebben met de respectievelijke vier bronvermeldingen.
[thesaus.ttl.txt](https://github.com/bimloket/CB-NL/files/6516921/thesaus.ttl.txt)

**Comment by RiX012** [comment]
> 
> 
> Ik heb op ons afgelopen besluit een vocabulair te maken een ontologietje gedefinieerd waarin een concept kan worden geinstantieeerd met verplicht een definitie en een bronvermelding en tot 4 alternatieve definities kan hebben met de respectievelijke vier bronvermeldingen.
> [thesaus.ttl.txt](https://github.com/bimloket/CB-NL/files/6516988/thesaus.ttl.txt)

@bartbink Ik heb de file even in de GitHub code gezet zodat we er ook echt versiegebaseerd wat mee kunnen. Staat hier: https://github.com/bimloket/CB-NL/blob/0d83ad9ec51af25eb7834d5169242208551a5b0f/ontology/template_voc/thesaus.ttl

**Comment by PaulHaase12** [comment]
[210608 AOA Begrippen- en Definities opmHS-PH.xlsx](https://github.com/bimloket/CB-NL/files/6617364/210608.AOA.Begrippen-.en.Definities.opmHS-PH.xlsx)

Henny en ik hebben vanuit de ABDL een selectie gemaakt van begrippen die we wel/niet kunnen opnemen in de CB-NL

**Comment by bartbink** [comment]
Zijn dit de kandidaten vanuit het NEN 2767 persectief?

**Comment by NielsHoffmann** [comment]
@bartbink Ik heb de abdl lijst gereviewed en wat mij betreft komen er flink veel meer concepten bij uit deze lijst voor de thesaurus. Voor de kern ontologie valt het wel mee....
Voor de thesaurus zou ik in ieder geval ook alle begrippen opnemen die uit de NEN2660 komen. En ook alle begrippen die anderszins uit INSPIRE, crow publicaties of andere wet- of regelgeving komen. daarmee dek je ook meteen de materialenpaspoort en SE achtige casussen af die we in de toekomst wellicht willen ondersteunen. 

Voor het kernmodel (de ontologie) zou ik veel van die begrippen niet meteen opnemen, alhoewel het wel helpt om duidelijke 'haakjes' te hebben waar bepaalde begrippen geplaatst zouden moeten worden in een extensie op de CB-NL ontologie. Misschien kunnen we dus een (beperkt) kern model maken en al een 'extensie' die illustratief is hoe het kernmodel uitgebreid kan worden. Daarvoor heb ik in kolom    D de gele kleur gebruikt.

**Comment by bartbink** [comment]
Beste Niels,

Ik ben nog niet door de gekleurde ABDL lijst heen gegaan. Het is inderdaad zo dat de thesaurus zo volledig mogelijk moet zijn. Als je een concept zoekt, zou die in de thesaurus moeten staan. Dus JA met je eens. Dat is ook wat ik heb doorgegeven aan de klankbordgroep.

Het kernmodel (met strenge RDFS hiërarchie) moet haakjes hebben voor de verschillende domeinen/kennisgebieden. Dus ook hier JA met je eens. @Michel Bohms (is kennelijk nog geen lid van GitHub) @Rik en ik zijn we door de lijst van IMBOR gegaan en hebben die zaken in het kernmodel opgenomen volgens NEN2660. Wat lastig is.

Zojuist ook overleg gehad met Henny en Jaap om extentie voorbeelden te maken. Daarvoor hebben we de URI's nodig van bijvoorbeeld IMBOR (ook al bestaat deze wellicht nog niet).

**Comment by rik** [comment]
I'm probably not the @rik you want to notify 😀 (I can't even read Dutch 😉)

**Comment by PaulHaase12** [comment]
Ik heb nog de lijst aangevuld met de ontbrekende concepten van de NEN 2767 die Mick mij heeft aangeleverd. Ik ben verder gegaan in het document waarin ook Niels H kleuren heeft toegevoegd. 

Ik heb een (grotendeels) de groenconcepten, waterzuiveringsconcepten, de speel- en sportitems en een paar echte onzin dingen eruit gehaald. Aan de andere kant als we een uitgebreide thesaurus willen waarom zou je dan niet alles opnemen? In principe heb ik bovenstaande zaken nu op rood gezet omdat het twijfelachting is of ze bij de scope van de CB-NL horen en er anders wellicht andere standaarden beter voldoen voor bovenstaande onderwerpen.

**Comment by RiX012** [comment]
> I'm probably not the @rik you want to notify 😀 (I can't even read Dutch 😉)

No you're not, it's me!

**Comment by nreyngou** [comment]
> Ik heb een (grotendeels) de groenconcepten, waterzuiveringsconcepten, de speel- en sportitems en een paar echte onzin dingen eruit gehaald. Aan de andere kant als we een uitgebreide thesaurus willen waarom zou je dan niet alles opnemen? In principe heb ik bovenstaande zaken nu op rood gezet omdat het twijfelachting is of ze bij de scope van de CB-NL horen en er anders wellicht andere standaarden beter voldoen voor bovenstaande onderwerpen.

Goede vraag. Hebben we het hier over de 'bouw', de gebouwde omgeving, de openbare ruimte, of de fysieke leefomgeving? 
Ik neig naar het laatste en denk dat ze er bij horen. Zeker als we CB-NL bruikbaar willen maken voor opdrachtgevers als waterschappen en gemeentes.

**Comment by bartbink** [comment]
> Ik heb nog de lijst aangevuld met de ontbrekende concepten van de NEN 2767 die Mick mij heeft aangeleverd. Ik ben verder gegaan in het document waarin ook Niels H kleuren heeft toegevoegd.
> 

Waar kan ik die lijst vinden? ik zie het niet onder input staan. Wel een oude lijst van 14 dagen geleden?

**Comment by NielsHoffmann** [comment]
@bartbink volgens mij hier: https://github.com/bimloket/CB-NL/tree/main/ontology/input/abdl

**Comment by bartbink** [comment]
> @bartbink volgens mij hier: https://github.com/bimloket/CB-NL/tree/main/ontology/input/abdl

Cheers!
