### ISSUE TITLE
CB-NL 2.0 en tegenstrijdigheid met NEN 2660-2

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/CB-NL#52]
In principe zou CB-NL alleen moeten bestaan uit extensies van de NEN 2660-2; anders zou CB-NL het topmodel van NEN 2660-2 uitbreiden en daarmee wijzigen. Door verschil van inzicht tussen de experts zijn er toch invoegingen ontstaan in het NEN 2660-2 model. Daarom is voor nu gekozen, deze concepten uit de beheeromgeving te houden, en deze met de nieuwe publicatie (CB-NL 2.1) niet mee te nemen. 

Daarom deze issue: te beoordelen wat moet worden ingebracht bij de NEN 2660-2, als eventuele aanvulliing of om te duiden waar deze concepten wel geplaatst zouden moeten worden.
[CB-NL_excluded_concepten_shortlist.csv](https://github.com/bimloket/CB-NL/files/11596833/CB-NL_excluded_concepten_shortlist.csv)

Vervolgens moet gekeken worden, wat de juiste plaats is van de onderliggende concepten, die nu wezen geworden zijn. [CB-NL_excluded_concepten_longlist.csv](https://github.com/bimloket/CB-NL/files/11596829/CB-NL_excluded_concepten_longlist.csv)

**Comment by bartbink** [comment]
De concepten als systeemdeel, bouwdeel en installatiedeel komen veel voor in standaarden. Men zoekt op deze concepten. Tijdens de productie van CBNL 2.0 is overeengekomen dat allerlei soorten onderdelen rollen zijn.

Zo is systeemelement, element, bouwdeel opgenomen. Deze concepten kunnen als anker dienen voor IFC, NEN2767 etc.

Functie is al voorzien in de Nen2660-2: Functional entity. Dit gaf echter discussie. Is een functie niet een activiteit? Of is het de potentie om iets te kunnen doen dat bij activatie wordt uitgevoerd. 'functie' is daarom opgenomen als subclass van activiteit
Activiteit is al voorzien in de Nen2660-2: Activity

Lijsten met functies en activiteiten

**Comment by ElisabethKloren** [comment]
De beheercommissie wil graag een oplossing, waarbij we geen concepten invoegen tussen de NEN 2660-2, maar "netjes" concepten toevoegen als afgeleide van de nen 2660-2

**Comment by bartbink** [comment]
Welke concepten zijn invoegingen? Heb je voorbeelden?

**Comment by bartbink** [comment]
In het overleg met Expertgroep is besproken NEN2660-1 te incorpereren in de publicatie van de CBNL!

Als de NEN 2660-2 gelezen wordt ziet men:

- 	Een logisch gevolg van de keuze om geen MetaRol op te nemen in het metamodel op te nemen zorgt er ook voor dat we op dit niveau wat specifieker omgaan met rollen. In plaats van een TopRol introduceren we functionele en technische entiteiten onder TopConcept.
Dit houdt in dat fuctionele en technische entitieten TopRollen of Rollen zijn. Dat houdt in dat de algemenere Rol wegvalt!
	Tevens is in NEN2660-1 TopRol een rol van de TopRelatie in één van de twee richtingen en niet het Concept Rol zoals Vader. Wat bedoelt wordt met TopRol is bijvoorbeeld met de relatie skos:prefLabel, de rol van het concept dat een preflabel toegedicht krijgt en de rol van het label dat de rol preferente label heeft.

- TopVerzameling als root wordt ook niet gebruikt. Verzamelingen worden ook onder TopConcept gehangen.
	Verzameling onder TopConcept betekent dat er geen gebruik wordt gemaakt van skos:Collection en dat daarmee in deze de skos binding skos:Collection niet wordt benut.

**Keuzes**:
	• Het concept Rol dat gebruikt kan worden als bijvoorbeeld Vader, de rol van een man dat een kind heeft gehad, is hetzelfde als TopRol
	• Het concept Verzameling is NIET skos:Collection, maar een skos:Concept te weten TopVerzameling. Hiermee verliest men de aan de skos:Collection verbonden eigenschappen bij een implementatie.

Verder valt op dat in de skos binding als concept zijn opgenomen.
De relaties in de skos binding zijn als skos:Concept gecast i.p.v. Rdf:Property en owl:AnnotationProperty. Dat kan alsnog gebeuren voor een aantal relaties.

beeindigt
begint
heeft begrenzing
heeft deel
heeft inwendige
heeft temporele entiteit
heeft toestand
is berschreven door
transformeert
triggert
voert uit
Eenheid
Kwantiteitsoort  [nen2660-term:QuantityKind]
Top Ding
aandeel
aggregatie toestand type
bestaat uit
bevat
chemische formule
eis bron type
eis ernst type	
eis onderwerp type
heeft delen groep
heeft eenheid
heeft eis
heeft kwantiteitsoort
heeft oplossing
is begrensd door
is plan voor
is verbonden met
over raakvlak
over verbinding
overdrachts type
participeert in
verbindt object
verbindt poort
verificatie methode type

**Comment by ElisabethKloren** [comment]
Besluit door productmanager: we gaan mee met de pragmatische keuzes uit NEN 2660-2, en voegen niet NEN 2660-1 toe. 

Zie verder #57
