### ISSUE TITLE
QUDT ontologie en ontbrekende grootheden

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/CB-NL#53]
waarom bevat CB-NL eenheden, kunnen we niet de eenheden uit [QUDT](https://github.com/qudt/qudt-public-repo) gebruiken als standaard voor de bouwsector? Deze wordt ook van toepassing verklaard in de NEN 2660-2.

**Comment by bartbink** [comment]
Er zijn eenheden die niet door QUDT worden gedekt. Die kunnen hieronder vallen.

**Comment by ElisabethKloren** [comment]
We nemen QUDT niet over, dan blijft staan deze vraag:

 prijs, adres, coördinaat en dergelijke nemen we niet mee in deze release van CB-NL, omdat het niet past in het topmodel van de NEN 2660-2

Dit gaan we vragen aan de opstellers van NEN 2660-2
